#!/usr/bin/env bash
set -e

IFS= read -r header

index=0

init_suite() {
  count=0
  failures=0
  skipped=0
  suitetest_exec_time=0
  name=""
  _buffer=""
}

finish_suite() {
  [[ ${count} -gt 0 ]] && {
    (
      flush_log
      header
      flush
      footer
    ) > "TestReport-${class-case}.xml"
  }
  init_suite
}

trap finish_suite EXIT

#reset=$(tput sgr0)
reset="\e[0m"
green="\e[32m"
red="\e[31m"
cyan="\e[36m"

skipped=0
failed=0
passed=0

while IFS= read -r line; do
  a=($line)
  case "$line" in
  "suite "*)
    ;;
  "ok "* )
    if [ "${a[2]} ${a[3]} " == "# skip " ]; then
      echo -e "  ${cyan}- skipped: ${a[@]:4}${reset}"
      let skipped+=1
    else
      echo -e "  ${green}✓ ${a[@]:2}${reset}"
      let passed+=1
    fi
    ;;
  "not ok "* )
    echo -e "  ${red}✗ ${a[@]:3}${reset}"
    let failed+=1
    ;;
  "# "* )
    echo -e "     ${red}${a[@]:1}${reset}"
    ;;
  esac
done

echo
echo "$(( ${failed} + ${passed} +  ${skipped} )) tests, ${failed} failure, ${skipped} skipped"

[ "${failed}" == "0" ] && exit 0 || exit 1

