#!/usr/bin/env bash
set -e

IFS= read -r header

index=0

init_suite() {
  count=0
  failures=0
  skipped=0
  suitetest_exec_time=0
  name=""
  _buffer=""
}

finish_suite() {
  [[ ${count} -gt 0 ]] && {
    (
      flush_log
      header
      flush
      footer
    ) > "TestReport-${class-case}.xml"
  }
  init_suite
}

trap finish_suite EXIT

reset=$(tput sgr0)
green=$(tput setaf 2)
red=$(tput setaf 1)
yellow=$(tput setaf 3)
cyan=$(tput setaf 6)

tests_skipped=0
tests_failed=0
tests_passed=0

while IFS= read -r line; do
  a=($line)
  case "$line" in
  "suite "*)
    ;;
  "ok "* )
    if [ "${a[2]} ${a[3]} " == "# skip " ]; then
      echo -e "  ${cyan}- skipped: ${a[@]:4}${reset}"
      let tests_skipped+=1
    else
      echo -e "  ${green}✓ ${a[@]:2}${reset}"
      let tests_passed+=1
    fi
    ;;
  "not ok "* )
    echo -e "  ${red}✗ ${a[@]:3}${reset}"
    let tests_failed+=1
    ;;
  "# "* )
    echo -e "     ${red}${a[@]:1}${reset}"
    ;;
  esac
done

echo
echo "$(( ${tests_failed} + ${tests_passed} +  ${tests_skipped} )) tests, ${tests_failed} failure, ${tests_skipped} skipped"

[ "${tests_failed}" == "0" ] && exit 0 || exit 1

